import pandas as pd

constituency_to_state = {
'AJMER': 'Rajasthan',
    'ALWAR': 'Rajasthan',
    'AMBALA': 'Haryana',
    'ANANTNAG-RAJOURI': 'Jammu & Kashmir',
    'ARAKKONAM': 'Tamil Nadu',
    'ARANI': 'Tamil Nadu',
    'Adilabad': 'Telangana',
    'Agra': 'Uttar Pradesh',
    'Ahmedabad East': 'Gujarat',
    'Ahmedabad West': 'Gujarat',
    'Ahmednagar': 'Maharashtra',
    'Akbarpur': 'Uttar Pradesh',
    'Akola': 'Maharashtra',
    'Alappuzha': 'Kerala',
    'Alathur': 'Kerala',
    'Aligarh': 'Uttar Pradesh',
    'Alipurduars': 'West Bengal',
    'Allahabad': 'Uttar Pradesh',
    'Almora': 'Uttarakhand',
    'Amalapuram (SC)': 'Andhra Pradesh',
    'Ambedkar Nagar': 'Uttar Pradesh',
    'Amethi': 'Uttar Pradesh',
    'Amravati': 'Maharashtra',
    'Amreli': 'Gujarat',
    'Amritsar': 'Punjab',
    'Amroha': 'Uttar Pradesh',
    'Anakapalle': 'Andhra Pradesh',
    'Anand': 'Gujarat',
    'Anandpur Sahib': 'Punjab',
    'Ananthapur': 'Andhra Pradesh',
    'Andaman & Nicobar Islands': 'Andaman and Nicobar Islands',
    'Aonla': 'Uttar Pradesh',
    'Araku (ST)': 'Andhra Pradesh',
    'Arambagh': 'West Bengal',
    'Araria': 'Bihar',
    'Arrah': 'Bihar',
    'Arunachal East': 'Arunachal Pradesh',
    'Arunachal West': 'Arunachal Pradesh',
    'Asansol': 'West Bengal',
    'Aska': 'Odisha',
    'Attingal': 'Kerala',
    'Aurangabad': 'Bihar',
    'Azamgarh': 'Uttar Pradesh',
    'BALAGHAT': 'Madhya Pradesh',
    'BANSWARA': 'Rajasthan',
    'BARAMULLA': 'Jammu & Kashmir',
    'BARMER': 'Rajasthan',
    'BASTAR': 'Chhattisgarh',
    'BETUL': 'Madhya Pradesh',
    'BHARATPUR': 'Rajasthan',
    'BHILWARA': 'Rajasthan',
    'BHIND': 'Madhya Pradesh',
    'BHIWANI-MAHENDRAGARH': 'Haryana',
    'BHOPAL': 'Madhya Pradesh',
    'BIKANER': 'Rajasthan',
    'BILASPUR': 'Chhattisgarh',
    'Badaun': 'Uttar Pradesh',
    'Bagalkot': 'Karnataka',
    'Baghpat': 'Uttar Pradesh',
    'Baharaich': 'Uttar Pradesh',
    'Baharampur': 'West Bengal',
    'Balasore': 'Odisha',
    'Ballia': 'Uttar Pradesh',
    'Balurghat': 'West Bengal',
    'Banaskantha': 'Gujarat',
    'Banda': 'Uttar Pradesh',
    'Bangalore North': 'Karnataka',
    'Bangalore Rural': 'Karnataka',
    'Bangalore South': 'Karnataka',
    'Bangalore central': 'Karnataka',
    'Bangaon': 'West Bengal',
    'Banka': 'Bihar',
    'Bankura': 'West Bengal',
    'Bansgaon': 'Uttar Pradesh',
    'Bapatla (SC)': 'Andhra Pradesh',
    'Barabanki': 'Uttar Pradesh',
    'Baramati': 'Maharashtra',
    'Barasat': 'West Bengal',
    'Bardhaman Purba': 'West Bengal',
    'Bardhaman-Durgapur': 'West Bengal',
    'Bardoli': 'Gujarat',
    'Bareilly': 'Uttar Pradesh',
    'Bargarh': 'Odisha',
    'Barpeta': 'Assam',
    'Barrackpur': 'West Bengal',
    'Basirhat': 'West Bengal',
    'Basti': 'Uttar Pradesh',
    'Bathinda': 'Punjab',
    'Beed': 'Maharashtra',
    'Begusarai': 'Bihar',
    'Belgaum': 'Karnataka',
    'Bellary': 'Karnataka',
    'Berhampur': 'Odisha',
    'Bhadohi': 'Uttar Pradesh',
    'Bhadrak': 'Odisha',
    'Bhagalpur': 'Bihar',
    'Bhandara Gondiya': 'Maharashtra',
    'Bharuch': 'Gujarat',
    'Bhavnagar': 'Gujarat',
    'Bhiwandi': 'Maharashtra',
    'Bhongir': 'Telangana',
    'Bhubaneswar': 'Odisha',
    'Bidar': 'Karnataka',
    'Bijapur': 'Karnataka',
    'Bijnor': 'Uttar Pradesh',
    'Birbhum': 'West Bengal',
    'Bishnupur': 'Manipur',
    'Bolangir': 'Odisha',
    'Bolpur': 'West Bengal',
    'Bulandshahr': 'Uttar Pradesh',
    'Buldhana': 'Maharashtra',
    'Buxar': 'Bihar',
    'CHENNAI CENTRAL': 'Tamil Nadu',
    'CHENNAI NORTH': 'Tamil Nadu',
    'CHENNAI SOUTH': 'Tamil Nadu',
    'CHHINDWARA': 'Madhya Pradesh',
    'CHIDAMBARAM': 'Tamil Nadu',
    'CHITTORGARH': 'Rajasthan',
    'CHURU': 'Rajasthan',
    'COIMBATORE': 'Tamil Nadu',
    'CUDDALORE': 'Tamil Nadu',
    'Chalakudy': 'Kerala',
    'Chamarajanagar': 'Karnataka',
    'Chandauli': 'Uttar Pradesh',
    'Chandigarh': 'Chandigarh',
    'Chandni Chowk': 'Delhi',
    'Chandrapur': 'Maharashtra',
    'Chatra': 'Jharkhand',
    'Chevella': 'Telangana',
    'Chhota Udaipur': 'Gujarat',
    'Chikkballapur': 'Karnataka',
    'Chikkodi': 'Karnataka',
    'Chitradurga': 'Karnataka',
    'Chittoor(SC)': 'Andhra Pradesh',
    'Coochbehar': 'West Bengal',
    'Cuttack': 'Odisha',
    'DAMOH': 'Madhya Pradesh',
    'DAUSA': 'Rajasthan',
    'DEWAS': 'Madhya Pradesh',
    'DHAR': 'Madhya Pradesh',
    'DHARMAPURI': 'Tamil Nadu',
    'DINDIGUL': 'Tamil Nadu',
    'DURG': 'Chhattisgarh',
    'Dadar & Nagar Haveli': 'Dadra and Nagar Haveli and Daman and Diu',
    'Dahod': 'Gujarat',
    'Dakshina Kannada': 'Karnataka',
    'Daman & Diu': 'Dadra and Nagar Haveli and Daman and Diu',
    'Darbhanga': 'Bihar',
    'Darjeeling': 'West Bengal',
    'Darrang-Udalguri': 'Assam',
    'Davanagere': 'Karnataka',
    'Deoria': 'Uttar Pradesh',
    'Dhanbad': 'Jharkhand',
    'Dharwad': 'Karnataka',
    'Dhaurahra': 'Uttar Pradesh',
    'Dhenkanal': 'Odisha',
    'Dhubri': 'Assam',
    'Dhule': 'Maharashtra',
    'Diamond harbour': 'West Bengal',
    'Dibrugarh': 'Assam',
    'Dindori': 'Madhya Pradesh',
    'Diphu': 'Assam',
    'Domariyaganj': 'Uttar Pradesh',
    'Dum dum': 'West Bengal',
    'Dumka': 'Jharkhand',
    'ERODE': 'Tamil Nadu',
    'East Delhi': 'Delhi',
    'Eluru': 'Andhra Pradesh',
    'Ernakulam': 'Kerala',
    'Etah': 'Uttar Pradesh',
    'Etawah': 'Uttar Pradesh',
    'FARIDABAD': 'Haryana',
    'Faizabad': 'Uttar Pradesh',
    'Faridkot': 'Punjab',
    'Farrukhabad': 'Uttar Pradesh',
    'Fatehgarh Sahib': 'Punjab',
    'Fatehpur': 'Uttar Pradesh',
    'Fatehpur Sikri': 'Uttar Pradesh',
    'Firozabad': 'Uttar Pradesh',
    'Firozpur': 'Punjab',
    'GANGANAGAR': 'Rajasthan',
    'GUNA': 'Madhya Pradesh',
    'GURGAON': 'Haryana',
    'GWALIOR': 'Madhya Pradesh',
    'Gadchiroli - Chimur': 'Maharashtra',
    'Gandhinagar': 'Gujarat',
    'Garhwal': 'Uttarakhand',
    'Gautam Buddha Nagar': 'Uttar Pradesh',
    'Gaya': 'Bihar',
    'Ghatal': 'West Bengal',
    'Ghaziabad': 'Uttar Pradesh',
    'Ghazipur': 'Uttar Pradesh',
    'Ghosi': 'Uttar Pradesh',
    'Giridih': 'Jharkhand',
    'Godda': 'Jharkhand',
    'Gonda': 'Uttar Pradesh',
    'Gopalganj': 'Bihar',
    'Gorakhpur': 'Uttar Pradesh',
    'Gulbarga': 'Karnataka',
    'Guntur': 'Andhra Pradesh',
    'Gurdaspur': 'Punjab',
    'Guwahati': 'Assam',
    'HAMIRPUR': 'Uttar Pradesh',
    'HISAR': 'Haryana',
    'HOSHANGABAD': 'Madhya Pradesh',
    'Hajipur': 'Bihar',
    'Hamirpur': 'Himachal Pradesh',
    'Hardoi': 'Uttar Pradesh',
    'Haridwar': 'Uttarakhand',
    'Hassan': 'Karnataka',
    'Hathras': 'Uttar Pradesh',
    'Hatkanangale': 'Maharashtra',
    'Haveri': 'Karnataka',
    'Hazaribagh': 'Jharkhand',
    'Hindupur': 'Andhra Pradesh',
    'Hingoli': 'Maharashtra',
    'Hooghly': 'West Bengal',
    'Hoshiarpur': 'Punjab',
    'Howrah': 'West Bengal',
    'Hyderabad': 'Telangana',
    'INDORE': 'Madhya Pradesh',
    'Idukki': 'Kerala',
    'Inner Manipur': 'Manipur',
    'JABALPUR': 'Madhya Pradesh',
    'JAIPUR': 'Rajasthan',
    'JAIPUR RURAL': 'Rajasthan',
    'JALORE': 'Rajasthan',
    'JAMMU': 'Jammu & Kashmir',
    'JANJGIR-CHAMPA': 'Chhattisgarh',
    'JHALAWAR-BARAN': 'Rajasthan',
    'JHUNJHUNU': 'Rajasthan',
    'JODHPUR': 'Rajasthan',
    'Jadavpur': 'West Bengal',
    'Jagatsinghpur': 'Odisha',
    'Jahanabad': 'Bihar',
    'Jajpur': 'Odisha',
    'Jalandhar': 'Punjab',
    'Jalaun': 'Uttar Pradesh',
    'Jalgaon': 'Maharashtra',
    'Jalna': 'Maharashtra',
    'Jalpaiguri': 'West Bengal',
    'Jamnagar': 'Gujarat',
    'Jamshedpur': 'Jharkhand',
    'Jamui': 'Bihar',
    'Jangipur': 'West Bengal',
    'Jaunpur': 'Uttar Pradesh',
    'Jhanjharpur': 'Bihar',
    'Jhansi': 'Uttar Pradesh',
    'Jhargram': 'West Bengal',
    'Jorhat': 'Assam',
    'Joynagar': 'West Bengal',
    'Junagadh': 'Gujarat',
    'KALLAKURICHI': 'Tamil Nadu',
    'KANCHEEPURAM': 'Tamil Nadu',
    'KANGRA': 'Himachal Pradesh',
    'KANKER': 'Chhattisgarh',
    'KANNIYAKUMARI': 'Tamil Nadu',
    'KARAULI-DHOLPUR': 'Rajasthan',
    'KARNAL': 'Haryana',
    'KARUR': 'Tamil Nadu',
    'KHAJURAHO': 'Madhya Pradesh',
    'KHANDWA': 'Madhya Pradesh',
    'KHARGONE': 'Madhya Pradesh',
    'KORBA': 'Chhattisgarh',
    'KOTA': 'Rajasthan',
    'KRISHNAGIRI': 'Tamil Nadu',
    'KURUKSHETRA': 'Haryana',
    'Kachchh': 'Gujarat',
    'Kadapa': 'Andhra Pradesh',
    'Kairana': 'Uttar Pradesh',
    'Kaiserganj': 'Uttar Pradesh',
    'Kakinada': 'Andhra Pradesh',
    'Kalahandi': 'Odisha',
    'Kalyan': 'Maharashtra',
    'Kandhamal': 'Odisha',
    'Kannauj': 'Uttar Pradesh',
    'Kannur': 'Kerala',
    'Kanpur': 'Uttar Pradesh',
    'Kanthi': 'West Bengal',
    'Karakat': 'Bihar',
    'Karimganj': 'Assam',
    'Karimnagar': 'Telangana',
    'Kasaragod': 'Kerala',
    'Katihar': 'Bihar',
    'Kaushambi': 'Uttar Pradesh',
    'Kaziranga': 'Assam',
    'Kendrapara': 'Odisha',
    'Keonjhar': 'Odisha',
    'Khadoor Sahib': 'Punjab',
    'Khagaria': 'Bihar',
    'Khammam': 'Telangana',
    'Kheda': 'Gujarat',
    'Kheri': 'Uttar Pradesh',
    'Khunti': 'Jharkhand',
    'Kishanganj': 'Bihar',
    'Kodarma': 'Jharkhand',
    'Kokrajhar': 'Assam',
    'Kolar': 'Karnataka',
    'Kolhapur': 'Maharashtra',
    'Kolkata Dakshin': 'West Bengal',
    'Kolkata Uttar': 'West Bengal',
    'Kollam': 'Kerala',
    'Koppal': 'Karnataka',
    'Koraput': 'Odisha',
    'Kottayam': 'Kerala',
    'Kozhikode': 'Kerala',
    'Krishnanagar': 'West Bengal',
    'Kurnoolu': 'Andhra Pradesh',
    'Kushi Nagar': 'Uttar Pradesh',
    'Ladakh': 'Ladakh',
    'Lakhimpur': 'Assam',
    'Lakshadweep': 'Lakshadweep',
    'Lalganj': 'Bihar',
    'Latur': 'Maharashtra',
    'Lohardaga': 'Jharkhand',
    'Lucknow': 'Uttar Pradesh',
    'Ludhiana': 'Punjab',
    'MADURAI': 'Tamil Nadu',
    'MAHASAMUND': 'Chhattisgarh',
    'MANDI': 'Himachal Pradesh',
    'MANDLA': 'Madhya Pradesh',
    'MANDSOUR': 'Madhya Pradesh',
    'MAYILADUTHURAI': 'Tamil Nadu',
    'MIZORAM': 'Mizoram',
    'MORENA': 'Madhya Pradesh',
    'Machhlishahr': 'Uttar Pradesh',
    'Machilipatnam': 'Andhra Pradesh',
    'Madha': 'Maharashtra',
    'Madhepura': 'Bihar',
    'Madhubani': 'Bihar',
    'Mahabubabad': 'Telangana',
    'Maharajganj': 'Uttar Pradesh',
    'Mahbubnagar': 'Telangana',
    'Mahesana': 'Gujarat',
    'Mainpuri': 'Uttar Pradesh',
    'Malappuram': 'Kerala',
    'Maldaha Dakshin': 'West Bengal',
    'Maldaha Uttar': 'West Bengal',
    'Malkajgiri': 'Telangana',
    'Mandya': 'Karnataka',
    'Mathura': 'Uttar Pradesh',
    'Mathurapur': 'West Bengal',
    'Maval': 'Maharashtra',
    'Mavelikkara': 'Kerala',
    'Mayurbhanj': 'Odisha',
    'Medak': 'Telangana',
    'Medinipur': 'West Bengal',
    'Meerut': 'Uttar Pradesh',
    'Mirzapur': 'Uttar Pradesh',
    'Mizoram': 'Mizoram',
    'Mohali': 'Punjab',
    'Monghyr': 'Bihar',
    'Moradabad': 'Uttar Pradesh',
    'Mumbai North': 'Maharashtra',
    'Mumbai North Central': 'Maharashtra',
    'Mumbai North East': 'Maharashtra',
    'Mumbai North West': 'Maharashtra',
    'Mumbai South': 'Maharashtra',
    'Mumbai South Central': 'Maharashtra',
    'Munger': 'Bihar',
    'Murshidabad': 'West Bengal',
    'Muzaffarnagar': 'Uttar Pradesh',
    'Muzaffarpur': 'Bihar',
    'NABARANGPUR': 'Odisha',
    'NAGAON': 'Assam',
    'NAGAPATTINAM': 'Tamil Nadu',
    'NAGAUR': 'Rajasthan',
    'NAGINA': 'Uttar Pradesh',
    'NAINITAL-UDHAMSINGH NAGAR': 'Uttarakhand',
    'NALANDA': 'Bihar',
    'NAMAKKAL': 'Tamil Nadu',
    'NANDED': 'Maharashtra',
    'NANDURBAR': 'Maharashtra',
    'NARSAPURAM': 'Andhra Pradesh',
    'NARSARAOPET': 'Andhra Pradesh',
    'NASIK': 'Maharashtra',
    'NAVSARI': 'Gujarat',
    'NAGALAND': 'Nagaland',
    'NORTH EAST DELHI': 'Delhi',
    'NORTH GOA': 'Goa',
    'NORTH SIKKIM': 'Sikkim',
    'NORTH WEST DELHI': 'Delhi',
    'Nabarangpur': 'Odisha',
    'Nagaland': 'Nagaland',
    'Nagapattinam': 'Tamil Nadu',
    'Nagaur': 'Rajasthan',
    'Nagina': 'Uttar Pradesh',
    'Nainital-Udhamsingh Nagar': 'Uttarakhand',
    'Nalanda': 'Bihar',
    'Nalgonda': 'Telangana',
    'Nanded': 'Maharashtra',
    'Nandurbar': 'Maharashtra',
    'Nandyal': 'Andhra Pradesh',
    'Narasaraopet': 'Andhra Pradesh',
    'Nashik': 'Maharashtra',
    'Nathdwara': 'Rajasthan',
    'Navsari': 'Gujarat',
    'Neemuch': 'Madhya Pradesh',
    'Nellore': 'Andhra Pradesh',
    'New Delhi': 'Delhi',
    'Nilgiris': 'Tamil Nadu',
    'Nizamabad': 'Telangana',
    'North West Delhi': 'Delhi',
    'Nuapada': 'Odisha',
    'Nagarkurnool': 'Telangana',
    'Nainital': 'Uttarakhand',
    'Najibabad': 'Uttar Pradesh',
    'Nalgonda': 'Telangana',
    'Narasaraopet': 'Andhra Pradesh',
    'Narsapuram': 'Andhra Pradesh',
    'Nashik': 'Maharashtra',
    'Nathdwara': 'Rajasthan',
    'Navsari': 'Gujarat',
    'Neemuch': 'Madhya Pradesh',
    'Nellore': 'Andhra Pradesh',
    'New Delhi': 'Delhi',
    'Nilgiris': 'Tamil Nadu',
    'Nizamabad': 'Telangana',
    'North Goa': 'Goa',
    'North Sikkim': 'Sikkim',
    'North West Delhi': 'Delhi',
    'Nuh': 'Haryana',
    'Osmanabad': 'Maharashtra',
    'PUDUCHERRY': 'Puducherry',
    'PUNE': 'Maharashtra',
    'Palakkad': 'Kerala',
    'Palghar': 'Maharashtra',
    'Pali': 'Rajasthan',
    'Panchmahal': 'Gujarat',
    'Panipat': 'Haryana',
    'Panna': 'Madhya Pradesh',
    'Panvel': 'Maharashtra',
    'Parbhani': 'Maharashtra',
    'Patiala': 'Punjab',
    'Patna Sahib': 'Bihar',
    'Patna': 'Bihar',
    'Phulpur': 'Uttar Pradesh',
    'Pilibhit': 'Uttar Pradesh',
    'Pollachi': 'Tamil Nadu',
    'Ponnani': 'Kerala',
    'Porbandar': 'Gujarat',
    'Port Blair': 'Andaman and Nicobar Islands',
    'Puducherry': 'Puducherry',
    'Pune': 'Maharashtra',
    'Purulia': 'West Bengal',
    'Purnia': 'Bihar',
    'Pushkar': 'Rajasthan',
    'Raebareli': 'Uttar Pradesh',
    'Raichur': 'Karnataka',
    'Raigad': 'Maharashtra',
    'Raiganj': 'West Bengal',
    'Raigarh': 'Chhattisgarh',
    'Raipur': 'Chhattisgarh',
    'Rajahmundry': 'Andhra Pradesh',
    'Rajampet': 'Andhra Pradesh',
    'Rajkot': 'Gujarat',
    'Rajmahal': 'Jharkhand',
    'Rajnandgaon': 'Chhattisgarh',
    'Rajouri': 'Jammu and Kashmir',
    'Rajsamand': 'Rajasthan',
    'Ramanathapuram': 'Tamil Nadu',
    'Rampur': 'Uttar Pradesh',
    'Ranaghat': 'West Bengal',
    'Ranchi': 'Jharkhand',
    'Ratlam': 'Madhya Pradesh',
    'Ratnagiri': 'Maharashtra',
    'Rewa': 'Madhya Pradesh',
    'Rishikesh': 'Uttarakhand',
    'Rohtak': 'Haryana',
    'Rourkela': 'Odisha',
    'SABARKANTHA': 'Gujarat',
    'SAHARANPUR': 'Uttar Pradesh',
    'SALEM': 'Tamil Nadu',
    'SAMASTIPUR': 'Bihar',
    'SAMBALPUR': 'Odisha',
    'SASARAM': 'Bihar',
    'SATARA': 'Maharashtra',
    'SECUNDERABAD': 'Telangana',
    'SHAHJAHANPUR': 'Uttar Pradesh',
    'SHEOHAR': 'Bihar',
    'SHILLONG': 'Meghalaya',
    'SHIMLA': 'Himachal Pradesh',
    'SHIMOGA': 'Karnataka',
    'SHIVAGANGA': 'Karnataka',
    'SHOPIAN': 'Jammu & Kashmir',
    'SIDDHARTHNAGAR': 'Uttar Pradesh',
    'SIKAR': 'Rajasthan',
    'SILCHAR': 'Assam',
    'SINGHBHUM': 'Jharkhand',
    'SIRSA': 'Haryana',
    'SITAMARHI': 'Bihar',
    'SITAPUR': 'Uttar Pradesh',
    'SIVAGANGA': 'Tamil Nadu',
    'SONIPAT': 'Haryana',
    'SOUTH DELHI': 'Delhi',
    'SOUTH GOA': 'Goa',
    'SOUTH SIKKIM': 'Sikkim',
    'SPSR NELLORE': 'Andhra Pradesh',
    'Saharanpur': 'Uttar Pradesh',
    'Saharsa': 'Bihar',
    'Salem': 'Tamil Nadu',
    'Samastipur': 'Bihar',
    'Sambalpur': 'Odisha',
    'Sangli': 'Maharashtra',
    'Sangrur': 'Punjab',
    'Satara': 'Maharashtra',
    'Satna': 'Madhya Pradesh',
    'Seemandhra': 'Andhra Pradesh',
    'Sehore': 'Madhya Pradesh',
    'Seoni': 'Madhya Pradesh',
    'Shahdol': 'Madhya Pradesh',
    'Shahjahanpur': 'Uttar Pradesh',
    'Shajapur': 'Madhya Pradesh',
    'Sheikhpura': 'Bihar',
    'Sheohar': 'Bihar',
    'Shimoga': 'Karnataka',
    'Shirdi': 'Maharashtra',
    'Shivamogga': 'Karnataka',
    'Shivpuri': 'Madhya Pradesh',
    'Shrirampur': 'Maharashtra',
    'Sikar': 'Rajasthan',
    'Silchar': 'Assam',
    'Siliguri': 'West Bengal',
    'Sirmaur': 'Himachal Pradesh',
    'Sirohi': 'Rajasthan',
    'Sirsa': 'Haryana',
    'Sitamarhi': 'Bihar',
    'Sitapur': 'Uttar Pradesh',
    'Sivaganga': 'Tamil Nadu',
    'Sivasagar': 'Assam',
    'Siwan': 'Bihar',
    'Solapur': 'Maharashtra',
    'Sonipat': 'Haryana',
    'South Goa': 'Goa',
    'South Sikkim': 'Sikkim',
    'Srikakulam': 'Andhra Pradesh',
    'Sultanpur': 'Uttar Pradesh',
    'Sunam': 'Punjab',
    'Supaul': 'Bihar',
    'Surat': 'Gujarat',
    'Surendranagar': 'Gujarat',
    'Surguja': 'Chhattisgarh',
    'Suryapet': 'Telangana',
    'Sawai Madhopur': 'Rajasthan',
    'Sawantwadi': 'Maharashtra',
    'Sehore': 'Madhya Pradesh',
    'Shahapur': 'Maharashtra',
    'Shajapur': 'Madhya Pradesh',
    'Shimla': 'Himachal Pradesh',
    'Shimoga': 'Karnataka',
    'Shirdi': 'Maharashtra',
    'Shivamogga': 'Karnataka',
    'Shivpuri': 'Madhya Pradesh',
    'Shrirampur': 'Maharashtra',
    'Siddharth Nagar': 'Uttar Pradesh',
    'Sikar': 'Rajasthan',
    'Silchar': 'Assam',
    'Siliguri': 'West Bengal',
    'Sirmaur': 'Himachal Pradesh',
    'Sirohi': 'Rajasthan',
    'Sitamarhi': 'Bihar',
    'Sitapur': 'Uttar Pradesh',
    'Sivaganga': 'Tamil Nadu',
    'Sivasagar': 'Assam',
    'Siwan': 'Bihar',
    'Solapur': 'Maharashtra',
    'Sonipat': 'Haryana',
    'South Goa': 'Goa',
    'South Sikkim': 'Sikkim',
    'Srikakulam': 'Andhra Pradesh',
    'Sultanpur': 'Uttar Pradesh',
    'Sunam': 'Punjab',
    'Supaul': 'Bihar',
    'Surat': 'Gujarat',
    'Surendranagar': 'Gujarat',
    'Surguja': 'Chhattisgarh',
    'Suryapet': 'Telangana',
    'TAMIL NADU': 'Tamil Nadu',
    'TELANGANA': 'Telangana',
    'THANJAVUR': 'Tamil Nadu',
    'THIRUVANANTHAPURAM': 'Kerala',
    'TIRUCHIRAPPALLI': 'Tamil Nadu',
    'TIRUNELVELI': 'Tamil Nadu',
    'TIRUPPUR': 'Tamil Nadu',
    'TIRUVALLUR': 'Tamil Nadu',
    'TIRUVANANTHAPURAM': 'Kerala',
    'Tumkur': 'Karnataka',
    'UJJAIN': 'Madhya Pradesh',
    'UNNAO': 'Uttar Pradesh',
    'UTTARAKHAND': 'Uttarakhand',
    'Udaipur': 'Rajasthan',
    'Udhampur': 'Jammu & Kashmir',
    'Udupi': 'Karnataka',
    'Ujjain': 'Madhya Pradesh',
    'Unnao': 'Uttar Pradesh',
    'Uttara Kannada': 'Karnataka',
    'VADAKARA': 'Kerala',
    'VADODARA': 'Gujarat',
    'VALMIKINAGAR': 'Bihar',
    'VARANASI': 'Uttar Pradesh',
    'VIDISHA': 'Madhya Pradesh',
    'VILUPPURAM': 'Tamil Nadu',
    'VISAKHAPATNAM': 'Andhra Pradesh',
    'VIZIANAGARAM': 'Andhra Pradesh',
    'Vadakara': 'Kerala',
    'Vadodara': 'Gujarat',
    'Vaishali': 'Bihar',
    'Valsad': 'Gujarat',
    'Varanasi': 'Uttar Pradesh',
    'Vellore': 'Tamil Nadu',
    'Vidisha': 'Madhya Pradesh',
    'Vijayawada': 'Andhra Pradesh',
    'Viluppuram': 'Tamil Nadu',
    'Virudhunagar': 'Tamil Nadu',
    'Visakhapatnam': 'Andhra Pradesh',
    'Vizianagaram': 'Andhra Pradesh',
    'WAGHOLI': 'Maharashtra',
    'WAYANAD': 'Kerala',
    'WARDHA': 'Maharashtra',
    'WEST BENGAL': 'West Bengal',
    'Warangal': 'Telangana',
    'Wardha': 'Maharashtra',
    'Wayanad': 'Kerala',
    'West Bengal': 'West Bengal',
    'Yavatmal-Washim': 'Maharashtra',
    'Zahirabad': 'Telangana'
}


file_path = 'lok_sabha_election_results_2024.csv'

df = pd.read_csv(file_path)
df['State'] = df['Constituency'].map(constituency_to_state)


df.to_csv('updated_dataset.csv', index=False)
